name = input("HEY USER PLEASE ENTER YOUR BEAUTIFUL NAME!: ")
if(len(name)<10):
  print("HEY USER YOUR NAME CONTAIN LESS THEN 10 CHARACTERS!")
else:
  print("HEY USER YOUR NAME CONTAINS MORE THEN 10 CHARACTERS!")